name: Willian Vieira Blog
description: Blogging about programming languages or anything :)
meta_description: "Willian Vieira Rosa Programmer, java programmer, programador brasil, java brasil"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://willianvieira.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://willianvieira.github.io'
author:         'Willian Vieira Rosa'
theme: jekyll-theme-hacker
